# Generated by Django 4.0.6 on 2022-07-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
