# Generated by Django 4.0.6 on 2022-07-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorizeapp', '0004_remove_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
