# Generated by Django 4.0.6 on 2022-07-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorizeapp', '0006_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
