version: '3.10'
services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        env_file: .env
        ports:
            - '8000:8000'
        depends_on:
            - db
    db:
        image: postgres:14.4
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=bayonet
          - POSTGRES_DB=prodkfk
    zookeeper-server:
        image: 'bitnami/zookeeper:latest'
        ports:
          - '2181:2181'
        environment:
          - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        image: 'bitnami/kafka:latest'
        ports:
          - '9092:9092'
        environment:
          - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
          - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
          - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
          - zookeeper-server
volumes:
  postgres_data:

