version: '3.10'
services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        env_file: .env
        ports:
            - '8000:8000'
        depends_on:
            - db
    db:
        image: postgres:14.4
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=bayonet
          - POSTGRES_DB=prodkfk
volumes:
  postgres_data:

